config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games, only: [:index, :show, :new, :create, :update, :destroy]

  resources :tests, only: [:index]

  # Friend request resources, but with custom routes.
  get "friends", to: "friend_requests#index", as: "friends"
  post "friends", to: "friend_requests#create"
  patch "friends/:id", to: "friend_requests#update", as: "friend"
  delete "friends/:id", to: "friend_requests#destroy"

  # Singular routes that aren't resourceful.
  post "/games/:id", to: "games#process_choice", as: "process_choice"
  get "games/:id/result", to: "games#result", as: "result"
  get "welcome", to: "static_pages#welcome", as: "welcome"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "games#index"	
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player1, class_name: 'User'
  belongs_to :player2, class_name: 'User'
  validates :player1, presence: true
  validates :player2, presence: true
  validates :player1_score, presence: true
  validates :player2_score, presence: true
  validates :current_question_id, presence: true

  def next
    if player1_correct != 0 && player2_correct != 0
      self.player1_score += 1 if player1_correct == 1
      self.player2_score += 1 if player2_correct == 1
      self.current_question_id = Question.first.id # TODO: change this to a random question, given the topic, using GPT-3
      history << current_question_id
      self.player1_correct = 0
      self.player2_correct = 0
      self.player1_backup = player1_recent
      self.player2_backup = player2_recent
      self.player1_recent = -1
      self.player2_recent = -1
      
      save
    end
  end

  def answered(id, choice)
    correct = Question.find(current_question_id).options.find_index(&:correct)
    if player1_id == id
      self.player1_recent = choice
    else
      self.player2_recent = choice
    end

    if choice == correct.to_s
      if player1_id == id
        self.player1_correct = 1
      else
        self.player2_correct = 1
      end
    elsif player1_id == id
      self.player1_correct = -1
    else
      self.player2_correct = -1
    end

    save
  end

  def answered_by(id)
    if player1_id == id
      player1_correct != 0
    else
      player2_correct != 0
    end
  end

  def chosen_by(id, q)
    if id == player1_id
      player1_recent == -1 && player2_recent == -1 ? q.options[player1_backup.to_i] : q.options[player1_recent.to_i]
    else
      player1_recent == -1 && player2_recent == -1 ? q.options[player2_backup.to_i] : q.options[player2_recent.to_i]
    end
  end

  def winner
    if player2_accepted
      if player1_score > player2_score
        "The winner is #{player1.username}"
      elsif player1_score < player2_score
        "The winner is #{player2.username}"
      else
        'The game ended in a tie'
      end
    else
      ''
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: %i[show edit update destroy process_choice result]
  before_action :verify_player, only: %i[show process_choice result]

  # GET /games or /games.json
  def index
    @games = Game.where(player1_id: current_user.id, player2_accepted: true) + Game.where(player2_id: current_user.id, player2_accepted: true)
    @invites = Game.where(player2_id: current_user.id, player2_accepted: false)
  end

  # GET /games/1 or /games/1.json
  def show
    @question = Question.find(@game.current_question_id)
  end

  # GET /games/new
  def new
    @game = Game.new
    fr = current_user.friends.map { |f| f.requester_id == current_user.id ? f.requestee : f.requester}
    @friends = fr.map { |f| [f.username, f.id] }
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    @game.current_question_id = Question.first.id # TODO: change this to a random question, given the topic, using GPT-3
    @game.player1_id = current_user.id
    @game.history << @game.current_question_id

    respond_to do |format|
      if @game.save
        #TD: Notification
        format.html { redirect_to games_url, notice: 'Game was successfully created. Wait for your opponent to accept it before playing.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    if Game.update(params[:id], player2_accepted: true)
      #TD: Notification
      # TD: Make this the game-url
      redirect_to games_url, notice: 'Game was successfully accepted.'
    else
      redirect_to games_url, alert: 'Game could not be accepted, are you the invitee?'
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @winner = @game.winner
    @game.destroy
    #TD: Notification 

    respond_to do |format|
      format.html { redirect_to games_url, notice: "The game has ended. #{@winner}" }
      format.json { head :no_content }
    end
  end

  def process_choice
    if @game.answered_by(current_user.id)
      redirect_to game_url(@game), alert: 'You have already answered this question.'
      return
    end

    @game.answered(current_user.id, params[:choice])
    @game.next

    redirect_to result_path(@game), notice: 'Answer was successfully processed.'
  end

  def result
    @question = Question.find(@game.current_question_id)
    @correct = @question.options.find(&:correct)

    @choice = @game.chosen_by(current_user.id, @question)
  end 

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:player1_id, :player2_id, :topic)
  end

  def verify_player
    redirect_to games_url, alert: 'You are not a player of this game.' unless @game.player1_id == current_user.id || @game.player2_id == current_user.id
    redirect_to games_url, alert: 'This game has not been accepted yet.' unless @game.player2_accepted
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>
  <h1 class="is-size-3"><strong>New Game</strong></h1>
  <h1 class="is-size-3">Topic</h1>
  <p class="is-size-7">Choose the topic your TrivAI game should be about! It can be anything. (Except in the MVP, where it'll be predetermined lol)</p>
  <br>
  <div class="field">
    <div class="control">
      <%= f.input :topic, 
          autofocus: true,
          wrapper: false,
          label: false,
          input_html: { class: "input" }%>
    </div>
  </div>
  <br>
  <h1 class="is-size-3">Opponent</h1>
  <p class="is-size-7">Who from your friendlist should be the game-opponent? </p>
  <br>
  <div class="field">
    <div class="control">
      <div class="select">
        <%= f.input :player2_id,
          wrapper: false,
          label: false,
          as: :select,
          collection: @friends,
          input_html: { class: "select" } %>
      </div>
    </div>
  </div>
  <br>
  <div class="field">
    <div class="control">
      <%= f.button :submit, "Create A New Game", class: "button has-background-purple" %>
    </div>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>" class="card">
  <div class="card-content">
    <p class="title"><%=game.player1.username%> vs <%=game.player2.username%> </p>
    <p class="subtitle">Topic: <%= game.topic %></p>
    <% if game.player1_id = current_user.id %>
      <% if game.player1_correct != 0 %>
        <br>
      <% else %>
        <p class="mgt-n10">You Can Answer!</p>
      <% end %>
    <% elsif game.player2_correct != 0 %>
      <br>
    <% else %>
      <p class="mgt-n10">You Can Answer!</p>
    <% end %>
    <br>
    <p class="subtitle is-size-6">Score: <%= game.player1_score %> - <%= game.player2_score %></p>
    <!-- TD: Add element saying if it's answerable -->
  </div>
  <footer class="card-footer container">
    <% if game.player2_accepted %>
      <span class="card-footer-item"> </span>
      <%= button_to "Play Game", game_path(game), class: "card-footer-item button has-background-purple is-centered", method: :get %>
      <span class="card-footer-item"> </span>
    <% else %>
      <%= button_to "Accept Game", game_path(game), class: "card-footer-item button is-success", method: :patch%>
      <span class="card-footer-item"> </span>
      <%= button_to "Deny Game", game_path(game), class: "card-footer-item button is-danger", method: :delete %>
    <% end %>
  </footer>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-four-fifths">
      <h1 class="title">Ongoing Games <%= button_to "Create New Game", new_game_path, method: "get", class: "button has-background-purple", form: {style: 'display:inline-block;'} %></h1>
      <div class="games">
        <div class="grid-container">
          <% @games.each do |game| %>
            <span><%= render game %></span>
          <% end %>
        </div>
      </div>
      <hr>
      <h2 class="subtitle">Game Invites</h2>
      <div class="games">
        <div class="grid-container">
          <% @invites.each do |game| %>
            <span><%= render game %></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/games/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <%= link_to root_path, class: "is-secondary is-size-7" do %>
          <b>Back to Your Games</b>
        <% end%>
        <%= render "form", game: @game %>
      </div>
    </div>
  </div>
</section>

app/views/games/result.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered is-vcentered">
      <div class="column is-two-thirds">
        <h1 class="title">Question: <%= @question.text %></h1>
        <div class="box has-background-triviablue">
          <div class="columns is-centered">
            <div class="column is-two-thirds is-centered">
              <!-- Todo: Add text saying player will only get 1 point for a correct answer, if already answered. -->
              <h2 class="subtitle">You Answered:</h2>
              <div class="box has-background-purple">
                <p><%= @choice.text %></p>
              </div>
              <h2 class="subtitle is-6">The correct answer was:</h2>
              <div class="box has-background-purple">
                <p><%= @correct.text %></p>
              </div>
              <% if @choice == @correct %>
                <p class="is-4"><b>Congratulations! That's +1 Point</b></p>
              <% else %>
                <p class="is-4"><b>Sorry, that's incorrect.</b></p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="box">
          <div class="columns is-centered">
            <div class="column is-two-thirds is-centered">
              <% if @game.player1_correct == 0 && @game.player2_correct == 0 %>
                Both players have answered. Continue to the next round?
                <%= button_to game_path(@game), class: "button has-background-purple", method: :get do %>
                  <p><b>Next Round</b></p>
                <% end %>
              <% else %>
                Wait for your opponent to answer. For now you can go back to your games.
                <%= button_to games_path, class: "button has-background-purple", method: :get do %>
                  <p><b>Back to your Games</b></p>
                <% end %>
              <% end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/games/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered is-vcentered">
      <div class="column is-two-thirds">
        <div class="level">
          <div class="level-left">
            <h1 class="title">Question: <%= @question.text %></h1>
          </div>
          <div class="level-right">
            <%= button_to "End The Game", game_path(@game), class: "button is-danger", method: :delete %>
          </div>
        </div>
        <div class="box has-background-triviablue">
          <div class="columns is-centered">
            <div class="column is-two-thirds is-centered">
              <!-- Todo: Add text saying player will only get 1 point for a correct answer, if already answered. -->
              <h2 class="subtitle">Answers:</h2>
              <% @question.options.each_with_index do |o, idx| %>
                <%= link_to game_path(@game, choice: idx), class: "box has-background-purple", data: { turbo_method: :post } do %>
                  <p><b><%= (idx+65).chr %>)</b> <%= o.text %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>