config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games, only: [:index, :show, :new, :create, :update, :destroy]

  resources :tests, only: [:index]

  # Friend request resources, but with custom routes.
  get "friends", to: "friend_requests#index", as: "friends"
  post "friends", to: "friend_requests#create"
  patch "friends/:id", to: "friend_requests#update", as: "friend"
  delete "friends/:id", to: "friend_requests#destroy"

  # Singular routes that aren't resourceful.
  post "/games/:id", to: "games#process_choice", as: "process_choice"
  get "games/:id/result", to: "games#result", as: "result"
  get "welcome", to: "static_pages#welcome", as: "welcome"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "games#index"	
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :requestee, class_name: 'User'
  validates :confirmed, inclusion: { in: [true, false] }

  def confirm(user_id)
    update(confirmed: true) if requestee_id == user_id
  end

  def correct_name(user_id)
    requester_id == user_id ? requestee.username : requester.username
  end

  def cor_map(user_id)
    map = []
    u = requester_id == user_id ? requestee.username : requester.username
    map << u
    map << requester_id == user_id ? requestee.id : requester.id
    map
    
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :authenticate_user!

  # GET /friends
  def index
    @friends = current_user.friends
    @incoming = current_user.incoming_requests
    @outgoing = current_user.outgoing_requests
  end

  # POST /friends
  def create
    user = User.find_by(username: params[:search][:name])
    if user
      @request = FriendRequest.new(requester_id: current_user.id, requestee_id: user.id)

      if @request.save
        redirect_to friends_path, notice: 'Completed Sucessfully.'
      else
        redirect_to friends_path, alert: 'Something went wrong, try again.'
      end
    else
      redirect_to friends_path, alert: 'User not found.'
    end
  end

  # PATCH /friends/:id
  def update
    @request = FriendRequest.find(params[:id])
    if @request.confirm(current_user.id)
      redirect_to friends_path, notice: 'Completed Sucessfully.'
    else
      redirect_to friends_path, notice: 'Something went wrong, try again.'
    end
  end

  # DELETE /friends/:id
  def destroy
    @request = FriendRequest.find(params[:id])
    if @request.destroy
      redirect_to friends_path, notice: 'Completed Sucessfully.'
    else
      redirect_to friends_path, notice: 'Something went wrong, try again.'
    end
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_my_friends.html.erb
<div class="friends-grid">
  <% @friends.each do |u| %>
    <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <!-- add procedural grabber when gravatar -->
                <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= u.correct_name(current_user.id) %></p>
            </div>
          </div>
          <footer class="card-footer">
            <%= button_to "Remove Friend", friend_path(u), method: :delete, class: "button has-background-purple has-text-weight-semibold" %>
          </footer>
        </div>
      </div>
  <% end %>
</div>

app/views/friend_requests/_requests.html.erb
<p>Incoming:</p>
<div class="friends-grid">
  <% @incoming.each do |r| %>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <!-- add procedural grabber when gravatar -->
              <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= r.requester.username %></p>
          </div>
        </div>
        <footer class="card-footer">
          <%= button_to "Accept Request", friend_path(r), method: :patch, class: "button is-success has-text-weight-semibold" %>
          <%= button_to "Decline Request", friend_path(r), method: :delete, class: "button is-danger has-text-weight-semibold" %>
        </footer>
      </div>
    </div>
  <% end %>
</div>
<hr>
<p>Outgoing:</p>
<div class="friends-grid">
  <% @outgoing.each do |r| %>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <!-- add procedural grabber when gravatar -->
              <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= r.requestee.username %></p>
          </div>
        </div>
        <footer class="card-footer">
          <%= button_to "Cancel Request", friend_path(r), method: :delete, class: "button is-danger has-text-weight-semibold" %>
        </footer>
      </div>
    </div>
  <% end %>
</div>

app/views/friend_requests/_search_friends.html.erb
<%= simple_form_for :search do |f| %>
  <div class="form">
    <div class="control">
      <%= f.input :name,
                  wrapper: false,
                  required: false,  
                  label: false,
                  input_html: { class: "input" },
                  label_html: { class: "label" } %>
    </div>
  </div>

  <div class="form">
    <div class="control">
      <%= f.submit "Add Friend", class: "button has-background-purple" %>
    </div>
  </div>
<% end %>

app/views/friend_requests/index.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-two-thirds">
      <h1 class="title">Friends</h1>
      <% if @friends.empty? %>
        <p>You have no friends yet... Maybe add someone using the searchbar below!</p>
      <% else %>
        <%= render 'my_friends' %>
      <% end %>
      <br>
      <h2 class="subtitle">Friend Requests</h2>
      <% if @incoming.empty? && @outgoing.empty? %>
        <p>You have no incoming or outgoing requests.</p>
      <% else %>
        <%= render 'requests' %>
      <% end %>
      <br>
      <h2 class="subtitle">Add new Friend</h2>
      <%= render 'search_friends' %>
    </div>
  </div>
</section>