config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games, only: [:index, :show, :new, :create, :update, :destroy]

  resources :tests, only: [:index]

  # Friend request resources, but with custom routes.
  get "friends", to: "friend_requests#index", as: "friends"
  post "friends", to: "friend_requests#create"
  patch "friends/:id", to: "friend_requests#update", as: "friend"
  delete "friends/:id", to: "friend_requests#destroy"

  # Singular routes that aren't resourceful.
  post "/games/:id", to: "games#process_choice", as: "process_choice"
  get "games/:id/result", to: "games#result", as: "result"
  get "welcome", to: "static_pages#welcome", as: "welcome"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "games#index"	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrivAI - A GPT based Trivia Game</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar has-background-light">
      <div class="navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag('LogoRD.png', width: "30%") %>
        <% end %>
        
        <div class="navbar-burger">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div class="navbar-menu">
        <div class="navbar-start">
          <!-- TODO: Possibly add about page? -->
        </div>
        <div class="navbar-end">
          <% if user_signed_in? %>
            <div class="navbar-item">
              <p class="control"><%= link_to "Friends", friends_path, class: "is-purple has-text-weight-bold" %></p>
            </div>
            <div class="navbar-item" id="dd">
              <div class="dropdown">
                <span><%= current_user.username %>&nbsp;</span>
                <span class="icon is-small">
                  <i class="arrow down"></i>
                </span>
                <div class="dropdown-menu is-right" id="dropdown-menu" role="menu">
                  <div class="dropdown-content">
                    <%= link_to edit_user_registration_path do %>
                      <p class="dropdown-item">Account Settings</p>
                    <% end %>
                    <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
                      <p class="dropdown-item">Sign Out</p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <div class="navbar-item">
              <p class="control"><%= link_to "Login", new_user_session_path, class: "has-text-black" %></p>
            </div>
            <div class="navbar-item">
              <p class="control"><%= link_to "Sign Up", new_user_registration_path, class: "has-text-black" %></p>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <footer>
      <div class="content has-text-centered">
        <p><strong>TrivAI</strong>, created by Jeroen Brinkhorst, Jeske Groenheiden, Floris Reuvers and Leonne Snel. <br>
          Code is available on <a href="https://github.com/NotAtec/RU_ResearchNDevelopment">GitHub</a></p>
      </div>
    </footer>
  </body>
</html>